# Generated by Django 2.2.1 on 2019-05-26 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('naming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'repositories',
            },
        ),
        migrations.AlterField(
            model_name='concept',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='naming.Concept', verbose_name='Kind'),
        ),
        migrations.CreateModel(
            name='SyncMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naming.Context')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naming.Repository')),
            ],
        ),
    ]
