# Generated by Django 2.2.1 on 2019-05-25 17:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('naming', '0002_auto_20190525_1658'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='concept',
            unique_together={('owner', 'label', 'context')},
        ),
    ]
