# Generated by Django 2.2.1 on 2019-05-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0003_auto_20190525_1702'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='concept',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('owner', 'label', 'context'), name='unique_concept_per_owner_and_context'),
        ),
    ]
