# Generated by Django 2.2.1 on 2019-05-25 18:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0004_auto_20190525_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
