# Generated by Django 2.2.1 on 2019-05-25 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0005_auto_20190525_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='concept',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('key', 'owner'), name='unique_keys_per_owner'),
        ),
    ]
